### ISSUE TITLE
Initial design of reader

### ISSUE THREAD

**Issue by amcewen** [mcqn/nfc-st25r3916#1]
The initial use of this reader will be as a replacement for the RC522 reader currently used by [Museum in a Box](https://museuminabox.org).

Key features:
* An LED on the top, which illuminates when a card is detected.  This will need to be controlled by whatever is connected to the reader, so effectively it's an LED controlled by a GPIO on the 8-way connector.
* An 8-way 0.1" pitch header on the underside for connection to the main board.  Through-hole I think.
* 4 mounting holes (3.2mm diameter)

Here's a rough guide to where things sit above the Museum in a Box PCB:

![image](https://github.com/mcqn/nfc-st25r3916/assets/108468/d434cac4-2ac0-4ccc-bd34-29c321c90014)

For the 8-way header, from left-to-right as seen in that image above (the red component footprint is the surface-mount 0.1" header) it would be good if we can keep to this pin-out: `3V3`, `IRQ`, `GND`, `LED`, `MISO`, `MOSI`, `SCLK`, `CS`

**Comment by huffeec** [comment]
Closed with 4cfd301
