### ISSUE TITLE
Initial bring-up and tuning

### ISSUE THREAD

**Issue by amcewen** [mcqn/nfc-st25r3916#4]
With a couple of boards fabbed we're onto bring-up and tuning of the antenna.

Initial key capacitor and resistor values are:
* C303 = C310 = 22pF
* C306 = C309 = 15pF
* C300 = C313 = 220pF
* C315 = C316 = 150pF
* R300 = R302 = 2R4

**Comment by huffeec** [comment]
Closed with 4cfd301
