### ISSUE TITLE
Apply for OSHW certification

### ISSUE THREAD

**Issue by huffeec** [mcqn/nfc-st25r3916#6]
Follow the process used in the [My Baby's got LED application](https://github.com/mcqn/my-babys-got-led/issues/9) to receive OSHW registration for this board.

My Baby's got LED is licenced as [CERN-OHL-S v2.0 ](https://cern-ohl.web.cern.ch/) is this applicable to this hardware too?

The libraries referenced in the documentation are covered by [STMicroelectronics](https://github.com/mcqn/NFC-RFAL/blob/main/LICENSE) but are not software included in this application. I think we are applying as 'No software' here?

The documentation for MBGL is licenced as [[CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)]

#### We will need a name, version number and description for the application.

Eg "An RFID/NFC reader using the ST Microelectronics ST25R3916 chip. The board gives access via a header to power/gnd, four SPI pins, irq and a status led. The development and documentation for the board is available on github, and the board is manufactured by mcqn and sold on Tindie."

Should this include more detail, eg of modes available?
 
Tasks required to submit application to OSHW

- [x] Assign ibal number and add to catalogue
- [x] Confirm licence and add to repo
- [x] Decide on name and complete description

**Comment by amcewen** [comment]
I've made the repo public.

We should put the name somewhere on the silkscreen on the board too.

**Comment by huffeec** [comment]
Current silkscreen for the back of the board.
All the right information (I think), although not necessarily in the right order (or font)

![image](https://github.com/mcqn/nfc-st25r3916/assets/4748179/be4d1bf6-0fc8-4b2a-97ab-f3300ea27f4b)

**Comment by huffeec** [comment]
##### OSHW form details (draft)

SECTION 1 OF 4
Same as My Baby's got LED

SECTION 2 OF 4
This part of the form asks for information about the project you wish to certify. Information submitted here will appear on your project’s profile listing.

Project name: Vicino NFC/RFID board
Project version: r20240314
Have you previously registered a version(s) of your project with OSHWA? No
Project description: An RFID/NFC reader using the ST Microelectronics ST25R3916 chip. The board gives access via a header to power/gnd, four SPI pins, irq and a status led. The development and documentation for the board is available on github, and the board is manufactured by mcqn and sold on Tindie.

Project website: mcqn.com/ibal243
Primary Project Type: Electronics
Additional Project Types:  Electronics, 
Project Keywords: NFC, RFID

Where can the documentation be found for your project?: https://github.com/mcqn/nfc-st25r3916/blob/main/Examples.md

Does your project incorporate or build upon other open projects that are not currently certified by OSHWA? If so, use this space to cite those projects N/A

SECTION 3 OF 4
This part of the form asks for information about your project’s licensing. In order to qualify for OSHWA certification, you must have chosen an open source license for your hardware, your software (if any), and your documentation. Your licenses for each of these elements will appear on your project’s profile listing.

What license is your project's hardware licensed under? CERN
What license is your project's software licensed under? No Software **
What license is your project's documentation licensed under? CC BY-SA

YES x9

SECTION 4 of 4
As My Baby's got LED

** As much as I understand it I think the ST Microelectronics licence prohibits us including it here?
> 
> 5. No use, reproduction or redistribution of this software package may be done in any manner that would subject 
> this software package to any Open Source Terms (as defined below).
[https://github.com/stm32duino/ST25R3916/blob/main/LICENSE](https://github.com/stm32duino/ST25R3916/blob/main/LICENSE)

**Comment by huffeec** [comment]
> Your application us now under review by the OSHWA team. In most cases this review is completed in less than two weeks. Once it is complete you will be notified at the email address you provided in your application. If the team has questions they will reach out to you directly at the same email address. In the meantime, if you have any questions or concerns, please do not hesitate to contact us at [certification@oshwa.org](mailto:certification@oshwa.org).

**Comment by amcewen** [comment]
The sixty-first UK device certified:

> This email serves as official confirmation that your hardware
> 
> Vicino NFC/RFID board
> 
> has now officially been certified as open source hardware by the Open Source Hardware Association. Congratulations!
> 
> Your UID is:
> 
> UK000061
> 
> Your hardware is now listed in the certification directly located here:
> 
> https://certification.oshwa.org/list.html
